"""Module containing centralized column name definitions for the spreadsheet."""

ID = 'ID'
PERGUNTA = 'PERGUNTA'
LEVAR_PARA_PROVA = 'LEVAR PARA PROVA'
INFORMACAO_COMPLEMENTAR = 'INFO COMPLEMENTAR'
INFORMACAO_DETALHADA = 'INFO DETALHADA'
EXEMPLO1 = 'EXEMPLO 1'
EXEMPLO2 = 'EXEMPLO 2'
EXEMPLO3 = 'EXEMPLO 3'
TOPICO = 'TOPICO'
SUBTOPICO = 'SUBTOPICO'
BANCAS = 'BANCAS'
IMPORTANCIA = 'IMPORTANCIA'
TAGS = 'TAGS'

REQUIRED_COLUMNS = [
    ID,
    PERGUNTA,
    LEVAR_PARA_PROVA,
    INFORMACAO_COMPLEMENTAR,
    INFORMACAO_DETALHADA,
    EXEMPLO1,
    EXEMPLO2,
    EXEMPLO3,
    TOPICO,
    SUBTOPICO,
    BANCAS,
    IMPORTANCIA,
    TAGS
]