"""Module containing centralized column name definitions for the spreadsheet."""

ID = 'ID'
PERGUNTA = 'PERGUNTA'
MATCH = 'LEVAR PARA PROVA'
EXTRA_INFO_1 = 'INFO COMPLEMENTAR'
EXTRA_INFO_2 = 'INFO DETALHADA'
EXEMPLO_1 = 'EXEMPLO 1'
EXEMPLO_2 = 'EXEMPLO 2'
EXEMPLO_3 = 'EXEMPLO 3'
TOPICO = 'TOPICO'
SUBTOPICO = 'SUBTOPICO'
BANCAS = 'BANCAS'
ANO = 'ULTIMO ANO EM PROVA'
TAGS = 'TAGS'

REQUIRED_COLUMNS = [
    ID,
    PERGUNTA,
    MATCH,
    EXTRA_INFO_1,
    EXTRA_INFO_2,
    EXEMPLO_1,
    EXEMPLO_2,
    EXEMPLO_3,
    TOPICO,
    SUBTOPICO,
    BANCAS,
    ANO,
    TAGS
]